version: '3'
services:
  stock-mysql:
    container_name: stock-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: stock_exchange
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    restart: always

  app:
    container_name: stock-back
    build: .
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    ports:
      - 8080:8080
    command: mvn clean spring-boot:run
    depends_on:
      - stock-mysql
    restart: on-failure

#  stock-front:
#    container_name: stock-front
#    image: raphau/stock-front:latest
#    ports:
#      - 4200:80